name: Cypress Report
description: Creates Cypress Report

inputs:
  cache-path:
    description: 'path of the cypress cache'
    default: ".cache/Cypress"

  browser:
    description: "type of browser (only chrome is supported at the moment)"
    default: "chrome"

  spec:
    required: true
    description: "Cypress spec to execute"

runs:
  using: composite
  steps:  
    - name: Extract branch name
      shell: bash
      run: echo "branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Get Repository
      uses: actions/checkout@v4

    - name: Restore Node Modules Cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-v1-${{ steps.extract_branch.outputs.branch }}-${{ hashFiles('yarn.lock') }}

    - name: Restore Cypress Cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-path }}
        key: cypress-v1-${{ steps.extract_branch.outputs.branch }}-${{ hashFiles('yarn.lock') }}
    - name: Restore Cache
      uses: actions/cache@v4
      with:
        path: /home/runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.cache
        key: cache-v1-${{ steps.extract_branch.outputs.branch }}-${{ hashFiles('yarn.lock') }}

    - name: run-cypress-tests
      shell: bash
      env:
        CYPRESS_CACHE_FOLDER: "${{ inputs.cache-path }}"
      id: tests
      run: Cypress_tags="regression" npx cypress run --browser ${{ inputs.browser }} --spec "${{ inputs.spec }}" || true

    - name: archive-production-artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress
        path: |
          ./cypress/screenshots
          ./cypress/videos
          ./cypress/results
        retention-days: 2